// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" with { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/gfm.css.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/updates.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/QueryBuilder.tsx";
import * as $$2 from "./islands/SearchQuery.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/gfm.css.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/updates.tsx": $4,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/QueryBuilder.tsx": $$1,
    "./islands/SearchQuery.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
